[package]
name = "tfhe-versionable-derive"
version = "0.7.0"
edition = "2021"
keywords = ["versioning", "serialization", "encoding", "proc-macro", "derive"]
homepage = "https://zama.org/"
documentation = "https://docs.rs/tfhe_versionable_derive"
repository = "https://github.com/zama-ai/tfhe-rs"
license = "BSD-3-Clause-Clear"
description = "tfhe-versionable-derive: A set of proc macro for easier implementation of the tfhe-versionable traits"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
