[package]
name = "add_new_version"
edition = "2024"
version = "0.9.0"
license = "BSD-3-Clause-Clear"

[dependencies]
clap.workspace = true
minijinja = { version = "1.0", features = ["loader"] }
serde = { version = "1.0", features = ["derive"] }
cargo_toml = "0.22"
semver = { version = "1.0" }
