[pbs_params]
    lwe_dimension=724
    glwe_dimension=2
    polynomial_size=1024
    lwe_noise_distribution={GaussianStdDev=1.2597809688976277e-05}
    glwe_noise_distribution={GaussianStdDev=2.2737367544323206e-13}
    pbs_base_log= 20
    pbs_level= 1
    ks_base_log= 2
    ks_level= 7
    message_width= 2
    carry_width= 2
    ciphertext_width= 44
    log2_p_fail=-64 
    modulus_switch_type= "Standard"

[ntt_params]
    core_arch="WmmUnfoldPcg"
    min_pbs_nb= 10
    batch_pbs_nb= 16
    total_pbs_nb= 32
    ct_width= 44
    radix= 2
    stg_nb= 10
    prime_modulus="Solinas2_44_14"
    psi= 32
    delta= 5
[ks_params]
    width= 21
    lbx= 2
    lby= 32
    lbz= 3
[pc_params]
    ksk_pc= 4
    ksk_bytes_w= 64
    bsk_pc= 4
    bsk_bytes_w= 64
    pem_pc= 2
    pem_bytes_w= 64
    glwe_pc= 1
    glwe_bytes_w= 64
[regf_params]
    reg_nb= 64
    coef_nb= 32
[isc_params]
    min_iop_size= 4
    depth= 64
