[pbs_params]
    lwe_dimension=20
    glwe_dimension=1
    polynomial_size=2048
    lwe_noise_distribution={TUniformBound= 0}
    glwe_noise_distribution={TUniformBound= 0}
    pbs_base_log=23
    pbs_level=1
    ks_base_log=2
    ks_level=7
    message_width=2
    carry_width=2
    ciphertext_width=64
    log2_p_fail=-64 
    modulus_switch_type= "Standard"

[ntt_params]
    core_arch= {GF64=[5,6]}
    min_pbs_nb= 10
    batch_pbs_nb= 12
    total_pbs_nb= 32
    ct_width= 64
    radix= 2
    stg_nb= 11
    prime_modulus="GF64"
    psi= 32
    delta= 5
[ks_params]
    width= 21
    lbx= 2
    lby= 32
    lbz= 3
[pc_params]
    ksk_pc= 4
    ksk_bytes_w= 32
    bsk_pc= 4
    bsk_bytes_w= 32
    pem_pc= 2
    pem_bytes_w= 32
    glwe_pc= 1
    glwe_bytes_w= 32
[regf_params]
    reg_nb= 64
    coef_nb= 32
[isc_params]
    min_iop_size= 4
    depth= 64
