[default]
extend-ignore-identifiers-re = [
    # Related to serialized object
    "ser",
    "unser",
    # Used when dumping tfhe-rs parameters set into Sage format
    "ND.*",
    # Related to FHE strings example handling "banana"
    "ba",
    "enc_ba",
    # Example with string replacing "hello" with "herlo"
    "herlo",
    # Example in trivium
    "C9217BA0D762ACA1",
    "0x[0-9a-fA-F]+",
    "xrt_coreutil",
]

[files]
extend-exclude = [
    "backends/tfhe-cuda-backend/cuda/src/fft128/twiddles.cu",
    "backends/tfhe-cuda-backend/cuda/src/fft/twiddles.cu",
    "backends/tfhe-hpu-backend/config_store/**/*.link_summary",
    "*.cbor",
    "*.bcode",
]
