[package]
name = "wasm-par-mq-web-tests"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-par-mq = { path = "..", features = ["sync-api"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = "0.4"
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = { workspace = true }
console_error_panic_hook = "0.1"
