# Build tfhe-fft
name: cargo_build_tfhe_fft

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CHECKOUT_TOKEN: ${{ secrets.REPO_CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cargo-builds-fft:
    name: cargo_build_tfhe_fft/cargo-builds-fft (bpr)
    runs-on: ${{ matrix.runner_type }}

    strategy:
      matrix:
        runner_type: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: 'false'
          token: ${{ env.CHECKOUT_TOKEN }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # zizmor: ignore[stale-action-refs] this action doesn't create releases
        with:
          toolchain: stable
          override: true

      - name: Run pcc checks
        if: matrix.runner_type == 'ubuntu-latest'
        run: |
          sudo apt install -y libfftw3-dev
          make pcc_fft

      - name: Build release
        run: |
          make build_fft

      - name: Build release no-std
        run: |
          make build_fft_no_std
