# Start all benchmark jobs on Slab CI bot.
name: Start all benchmarks

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      # The input name must be the name of the slab command to launch
      boolean_bench:
        description: "Run Boolean benches"
        type: boolean
        default: true
      shortint_bench:
        description: "Run shortint benches"
        type: boolean
        default: true
      integer_bench:
        description: "Run integer benches"
        type: boolean
        default: true
      integer_multi_bit_bench:
        description: "Run integer multi bit benches"
        type: boolean
        default: true
      pbs_bench:
        description: "Run PBS benches"
        type: boolean
        default: true
      wasm_client_bench:
        description: "Run WASM client benches"
        type: boolean
        default: true

jobs:
  start-benchmarks:
    if: ${{ (github.event_name == 'push' && github.repository == 'zama-ai/tfhe-rs') || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        command: [boolean_bench, shortint_bench, integer_bench, integer_multi_bit_bench, pbs_bench, wasm_client_bench]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tfhe-rs
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          fetch-depth: 0

      - name: Check for file changes
        id: changed-files
        uses: tj-actions/changed-files@2a968ff601949c81b47d9c1fdb789b0d25ddeea2
        with:
          files_yaml: |
            benches:
              - toolchain.txt
              - Makefile
              - ci/slab.toml
              - tfhe/Cargo.toml
              - tfhe/src/**
              - tfhe/benches/**
              - tfhe/web_wasm_parallel_tests/**
              - .github/workflows/*_benchmark.yml
              - .github/workflows/start_benchmarks.yml

      - name: Checkout Slab repo
        if: github.event_name == 'workflow_dispatch' || steps.changed-files.outputs.benches_any_changed == 'true'
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          repository: zama-ai/slab
          path: slab
          token: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}

      - name: Start AWS job in Slab
        # If manually triggered check that the current bench has been requested
        # Otherwise if it's on push check that files relevant to benchmarks have changed
        if: (github.event_name == 'workflow_dispatch' && github.event.inputs[matrix.command] == 'true') || (github.event_name == 'push' && steps.changed-files.outputs.any_changed == 'true')
        shell: bash
        run: |
          echo -n '{"command": "${{ matrix.command }}", "git_ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}' > command.json
          SIGNATURE="$(slab/scripts/hmac_calculator.sh command.json '${{ secrets.JOB_SECRET }}')"
          curl -v -k \
          --fail-with-body \
          -H "Content-Type: application/json" \
          -H "X-Slab-Repository: ${{ github.repository }}" \
          -H "X-Slab-Command: start_aws" \
          -H "X-Hub-Signature-256: sha256=${SIGNATURE}" \
          -d @command.json \
          ${{ secrets.SLAB_URL }}
